### ISSUE TITLE
version 0.9.2 is failing on dropbox==2.2.0

### ISSUE THREAD

**Issue by joshowen** [sesh/piprot#47]
Traceback (most recent call last):
  File "/Users/josh/anaconda/envs/Openfolio/bin/piprot", line 11, in <module>
    sys.exit(piprot())
  File "/Users/josh/anaconda/envs/Openfolio/lib/python2.7/site-packages/piprot/piprot.py", line 442, in piprot
    url=cli_args.url)
  File "/Users/josh/anaconda/envs/Openfolio/lib/python2.7/site-packages/piprot/piprot.py", line 272, in main
    response=result['latest']\
  File "/Users/josh/anaconda/envs/Openfolio/lib/python2.7/site-packages/piprot/piprot.py", line 181, in get_version_and_release_date
    versions = {v: parse_version(v) for v in response['releases'].keys() if not parse_version(v).is_prerelease()}
  File "/Users/josh/anaconda/envs/Openfolio/lib/python2.7/site-packages/piprot/piprot.py", line 181, in <dictcomp>
    versions = {v: parse_version(v) for v in response['releases'].keys() if not parse_version(v).is_prerelease()}
  File "/Users/josh/anaconda/envs/Openfolio/lib/python2.7/site-packages/piprot/piprot.py", line 86, in parse_version
    return PiprotVersion(version)
TypeError: __init__() takes exactly 3 arguments (2 given)

**Comment by sesh** [comment]
@joshowen thanks for the bug report. I can't reproduce this one at the moment... Are you able to post your full requirements file?

I can see an issue with the code here, I just can't see how you're hitting that piece of code with `dropbox==2.2.0`

**Comment by joshowen** [comment]
I'm able to reproduce it with piprot 0.9.2 and dropbox==2.2.0

**Comment by joshowen** [comment]
I also get the following error with pytz==2015.4
  File "/Users/josh/anaconda/envs/Openfolio/bin/piprot", line 11, in <module>
    sys.exit(piprot())
  File "/Users/josh/anaconda/envs/Openfolio/lib/python2.7/site-packages/piprot/piprot.py", line 442, in piprot
    url=cli_args.url)
  File "/Users/josh/anaconda/envs/Openfolio/lib/python2.7/site-packages/piprot/piprot.py", line 272, in main
    response=result['latest']\
  File "/Users/josh/anaconda/envs/Openfolio/lib/python2.7/site-packages/piprot/piprot.py", line 182, in get_version_and_release_date
    version = max(versions.items(), key=operator.itemgetter(1))[0]
  File "/Users/josh/anaconda/envs/Openfolio/lib/python2.7/site-packages/piprot/piprot.py", line 70, in __lt__
    return self.__cmp__(other) < 0
  File "/Users/josh/anaconda/envs/Openfolio/lib/python2.7/site-packages/piprot/piprot.py", line 63, in __cmp__
    if other.is_prerelease():
AttributeError: 'int' object has no attribute 'is_prerelease'

**Comment by joshowen** [comment]
@sesh please see above

**Comment by joshowen** [comment]
Closing as this is now a duplicate of https://github.com/sesh/piprot/issues/48

**Comment by sesh** [comment]
@joshowen thanks for this one. It should be fixed in 0.9.4 which I've just pushed up to PyPI.
