### ISSUE TITLE
KeyError in  get_version_and_release_date

### ISSUE THREAD

**Issue by jedie** [sesh/piprot#73]
```
$ piprot --outdated requirements.txt
...
Traceback (most recent call last):
  File "/usr/local/bin/piprot", line 11, in <module>
    sys.exit(piprot())
  File "/usr/local/lib/python3.5/dist-packages/piprot/piprot.py", line 497, in piprot
    url=cli_args.url)
  File "/usr/local/lib/python3.5/dist-packages/piprot/piprot.py", line 317, in main
    req, version, response=result['specified'].result()
  File "/usr/local/lib/python3.5/dist-packages/piprot/piprot.py", line 192, in get_version_and_release_date
    release_date = response['releases'][version][0]['upload_time']
KeyError: '0.4.21'
```

It must come from `unidecode==0.4.21`
PyPi page: https://pypi.org/project/Unidecode/#history

**Comment by sesh** [comment]
@jedie can you install the master version with pip and test? This might not have been included in what was pushed to PyPI.

Also, have you thought about using the workaround of specifying the version as “0.04.21”? That’s how unidecode has specified the version number.
